quarkus.http.port=9999
quarkus.http.host=0.0.0.0

quarkus.jackson.property-naming-strategy=SNAKE_CASE

quarkus.log.level=WARN
quarkus.log.category."br.com.samueltorga".level=INFO

quarkus.smallrye-health.root-path=/q/health